
openapi: 3.0.0
info:
  title: a
  description: A sample.
  version: 1

servers:
  - url: http://localhost/cloudmesh/a
    description: Optional server description, e.g. Main (production) server
paths:
  /a:
     get:
        ....
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
